In [1]:
import numpy as np
import pandas as pd

<div class="alert alert-block alert-success">
    <h1 align="center">Machine Learning in Python</h1>
    <h3 align="center"> data preprocessing in machine learning</h3>
</div>

In [ ]:
data = pd.read_csv('pima-indians-diabetes.csv', names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'])
data.head()

In [ ]:
data.isnull().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [ ]:
data.isna().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [ ]:
skines = data[data['skin'] == 0]
skines

preg  plas  pres  skin  test  mass   pedi  age  class
2       8   183    64     0     0  23.3  0.672   32      1
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
9       8   125    96     0     0   0.0  0.232   54      1
10      4   110    92     0     0  37.6  0.191   30      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
757     0   123    72     0     0  36.3  0.258   52      1
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
762     9    89    62     0     0  22.5  0.142   33      0
766     1   126    60     0     0  30.1  0.349   47      1

[227 rows x 9 columns]

In [ ]:
data[data['skin'] != 0]['skin'].mean()

29.153419593345657

In [ ]:
skin_mean = data[data['skin'] != 0]['skin'].mean()

In [ ]:
len(data)

768

In [ ]:
data.replace({'skin': 0}, skin_mean, inplace=True)

In [ ]:
data

preg  plas  pres      skin  test  mass   pedi  age  class
0       6   148    72  35.00000     0  33.6  0.627   50      1
1       1    85    66  29.00000     0  26.6  0.351   31      0
2       8   183    64  29.15342     0  23.3  0.672   32      1
3       1    89    66  23.00000    94  28.1  0.167   21      0
4       0   137    40  35.00000   168  43.1  2.288   33      1
..    ...   ...   ...       ...   ...   ...    ...  ...    ...
763    10   101    76  48.00000   180  32.9  0.171   63      0
764     2   122    70  27.00000     0  36.8  0.340   27      0
765     5   121    72  23.00000   112  26.2  0.245   30      0
766     1   126    60  29.15342     0  30.1  0.349   47      1
767     1    93    70  31.00000     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [ ]:
data.describe()

preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   29.153420   79.799479   31.992578   
std      3.369578   31.972618   19.355807    8.790942  115.244002    7.884160   
min      0.000000    0.000000    0.000000    7.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000   25.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   29.153420   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [ ]:
test_mean = data[data['test'] != 0]['test'].mean()

In [ ]:
data.replace({'test': 0}, test_mean, inplace=True)

In [ ]:
data

preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [ ]:
data = pd.read_csv('pima-indians-diabetes.csv', names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'])
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
data.replace({'test': 0, 'skin': 0}, np.nan, inplace=True)

In [ ]:
data

preg  plas  pres  skin   test  mass   pedi  age  class
0       6   148    72  35.0    NaN  33.6  0.627   50      1
1       1    85    66  29.0    NaN  26.6  0.351   31      0
2       8   183    64   NaN    NaN  23.3  0.672   32      1
3       1    89    66  23.0   94.0  28.1  0.167   21      0
4       0   137    40  35.0  168.0  43.1  2.288   33      1
..    ...   ...   ...   ...    ...   ...    ...  ...    ...
763    10   101    76  48.0  180.0  32.9  0.171   63      0
764     2   122    70  27.0    NaN  36.8  0.340   27      0
765     5   121    72  23.0  112.0  26.2  0.245   30      0
766     1   126    60   NaN    NaN  30.1  0.349   47      1
767     1    93    70  31.0    NaN  30.4  0.315   23      0

[768 rows x 9 columns]

In [3]:
from sklearn.impute import KNNImputer

In [ ]:
imputer = KNNImputer(n_neighbors=3)
data = imputer.fit_transform(data)

In [ ]:
type(data)

numpy.ndarray

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [ ]:
print(data)

[[6.00000000e+00 1.48000000e+02 7.20000000e+01 3.50000000e+01
  1.25333333e+02 3.36000000e+01 6.27000000e-01 5.00000000e+01
  1.00000000e+00]
 [1.00000000e+00 8.50000000e+01 6.60000000e+01 2.90000000e+01
  6.66666667e+01 2.66000000e+01 3.51000000e-01 3.10000000e+01
  0.00000000e+00]
 [8.00000000e+00 1.83000000e+02 6.40000000e+01 3.00000000e+01
  1.95000000e+02 2.33000000e+01 6.72000000e-01 3.20000000e+01
  1.00000000e+00]
 [1.00000000e+00 8.90000000e+01 6.60000000e+01 2.30000000e+01
  9.40000000e+01 2.81000000e+01 1.67000000e-01 2.10000000e+01
  0.00000000e+00]
 [0.00000000e+00 1.37000000e+02 4.00000000e+01 3.50000000e+01
  1.68000000e+02 4.31000000e+01 2.28800000e+00 3.30000000e+01
  1.00000000e+00]
 [5.00000000e+00 1.16000000e+02 7.40000000e+01 1.83333333e+01
  1.09000000e+02 2.56000000e+01 2.01000000e-01 3.00000000e+01
  0.00000000e+00]
 [3.00000000e+00 7.80000000e+01 5.00000000e+01 3.20000000e+01
  8.80000000e+01 3.10000000e+01 2.48000000e-01 2.60000000e+01
  1.00000000e+00]
 [1.00

In [ ]:
data = data[:, :-1]

In [ ]:
data

array([[6.00000000e+00, 1.48000000e+02, 7.20000000e+01, 3.50000000e+01,
        1.25333333e+02, 3.36000000e+01, 6.27000000e-01, 5.00000000e+01],
       [1.00000000e+00, 8.50000000e+01, 6.60000000e+01, 2.90000000e+01,
        6.66666667e+01, 2.66000000e+01, 3.51000000e-01, 3.10000000e+01],
       [8.00000000e+00, 1.83000000e+02, 6.40000000e+01, 3.00000000e+01,
        1.95000000e+02, 2.33000000e+01, 6.72000000e-01, 3.20000000e+01],
       [1.00000000e+00, 8.90000000e+01, 6.60000000e+01, 2.30000000e+01,
        9.40000000e+01, 2.81000000e+01, 1.67000000e-01, 2.10000000e+01],
       [0.00000000e+00, 1.37000000e+02, 4.00000000e+01, 3.50000000e+01,
        1.68000000e+02, 4.31000000e+01, 2.28800000e+00, 3.30000000e+01],
       [5.00000000e+00, 1.16000000e+02, 7.40000000e+01, 1.83333333e+01,
        1.09000000e+02, 2.56000000e+01, 2.01000000e-01, 3.00000000e+01],
       [3.00000000e+00, 7.80000000e+01, 5.00000000e+01, 3.20000000e+01,
        8.80000000e+01, 3.10000000e+01, 2.48000000e-01, 2.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
data = scaler.fit_transform(data)

In [ ]:
data

array([[0.35294118, 0.74371859, 0.59016393, 0.30434783, 0.1338141 ,
        0.50074516, 0.23441503, 0.48333333],
       [0.05882353, 0.42713568, 0.54098361, 0.23913043, 0.06330128,
        0.39642325, 0.11656704, 0.16666667],
       [0.47058824, 0.91959799, 0.52459016, 0.25      , 0.21754808,
        0.34724292, 0.25362938, 0.18333333],
       [0.05882353, 0.44723618, 0.54098361, 0.17391304, 0.09615385,
        0.41877794, 0.03800171, 0.        ],
       [0.        , 0.68844221, 0.32786885, 0.30434783, 0.18509615,
        0.64232489, 0.94363792, 0.2       ],
       [0.29411765, 0.58291457, 0.60655738, 0.12318841, 0.11418269,
        0.38152012, 0.05251921, 0.15      ],
       [0.17647059, 0.3919598 , 0.40983607, 0.27173913, 0.08894231,
        0.46199702, 0.07258753, 0.08333333],
       [0.58823529, 0.57788945, 0.        , 0.25362319, 0.07451923,
        0.52608048, 0.02391119, 0.13333333],
       [0.11764706, 0.98994975, 0.57377049, 0.41304348, 0.63581731,
        0.45454545, 0.034158

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data = scaler.fit_transform(data)

In [ ]:
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.25703208e-01, -2.69421175e-01,  2.04012771e-01,
         4.68491977e-01,  1.42599540e+00],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -4.42144760e-03, -8.50042043e-01, -6.84421946e-01,
        -3.65060778e-01, -1.90671905e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         1.00599328e-01,  4.20066105e-01, -1.10325546e+00,
         6.04397318e-01, -1.05584152e-01],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -6.34546104e-01, -5.79525502e-01, -4.94043078e-01,
        -9.20762614e-01, -1.04154944e+00],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.25703208e-01,  1.52848546e-01,  1.40974560e+00,
         5.48490910e+00, -2.04963989e-02],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
        -1.12464306e+00, -4.31071303e-01, -8.11341192e-01,
        -8.18078579e-01, -2.75759658e-01],
       [-2.50952128e-01, -1.342476

In [ ]:
from sklearn.preprocessing import Normalizer
norm = Normalizer()
data = norm.fit_transform(data)

In [ ]:
data

array([[ 3.23625340e-01,  4.29002660e-01,  7.56742665e-02,
         3.16422034e-01, -1.36247977e-01,  1.03170537e-01,
         2.36919329e-01,  7.21134813e-01],
       [-4.60766647e-01, -6.12655617e-01, -8.75552539e-02,
        -2.41128136e-03, -4.63579063e-01, -3.73256461e-01,
        -1.99089604e-01, -1.03984860e-01],
       [ 4.61432755e-01,  7.26892185e-01, -9.87058045e-02,
         3.76210152e-02,  1.57091638e-01, -4.12583175e-01,
         2.26025770e-01, -3.94851839e-02],
       [-3.91754227e-01, -4.62846532e-01, -7.44414576e-02,
        -2.94224779e-01, -2.68712962e-01, -2.29076681e-01,
        -4.26936948e-01, -4.82943085e-01],
       [-1.89497384e-01,  8.36511049e-02, -2.49712237e-01,
         1.03839352e-01,  2.53661700e-02,  2.33956079e-01,
         9.10254889e-01, -3.40150528e-03],
       [ 1.96090100e-01, -8.75793454e-02,  1.44666712e-01,
        -6.42984598e-01, -2.46453492e-01, -4.63862632e-01,
        -4.67714554e-01, -1.57658211e-01],
       [-1.22479676e-01, -6.552089

In [ ]:
np.sum(data[0]**2)

0.9999999999999999

In [ ]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0)
data_b = binarizer.fit_transform(data)

In [ ]:
data_b

array([[1., 1., 1., 1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0., 1.],
       [1., 1., 1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 0., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 0., 0., 0., 0.],
       [1., 1., 

In [ ]:
np.concatenate((data, data_b), axis=1)

array([[ 3.23625340e-01,  4.29002660e-01,  7.56742665e-02,
         3.16422034e-01, -1.36247977e-01,  1.03170537e-01,
         2.36919329e-01,  7.21134813e-01,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [-4.60766647e-01, -6.12655617e-01, -8.75552539e-02,
        -2.41128136e-03, -4.63579063e-01, -3.73256461e-01,
        -1.99089604e-01, -1.03984860e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 4.61432755e-01,  7.26892185e-01, -9.87058045e-02,
         3.76210152e-02,  1.57091638e-01, -4.12583175e-01,
         2.26025770e-01, -3.94851839e-02,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-3.91754227e-01, -4.62846532e