In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('per.csv')
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [3]:
with open('stopwords.txt') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/masoud/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1495

In [7]:
import hazm
stemmer = hazm.Stemmer()

In [10]:
stemmer.stem('استادها')

'استاد'

In [11]:
lem = hazm.Lemmatizer()

In [18]:
lem.lemmatize('می‌آییم')

'آمد#آ'

In [19]:
from hazm import word_tokenize

In [27]:
r = data.iloc[0]
r = r['Title'] + r['Body']
r

'\nوزير علوم درجمع استادان نمونه: سن بازنشستگي استادان نمونه به 70 سال افزايش مي\u200cيابد دانشگاه بايد مهد چالشهاي گفتماني و خط دهنده و برنامه\u200cريز جريانات سياسي باشد\nوزير علوم در جمع استادان نمونه كشور گفت: از استادان نمونه كشور انتظار مي\u200cرود كه رويكرد دانايي محوري و گفتمان علمي را به عنوان يك بحث فرهنگي در دانشگاهها توسعه و رونق بخشند. به گزارش سرويس صنفي آموزشي خبرگزاري دانشجويان ايران (ايسنا)، دكتر محمد مهدي زاهدي در اولين مجمع عمومي استادان نمونه دانشگاه\u200cهاي سراسر كشور كه در دانشگاه تهران برگزار شد، افزود: توصيه ما در جهت تلاش براي دانايي محوري و توسعه گفتمان علمي به معني عدم تمايل به مباحث سياسي نيست؛ بلكه برعكس، دانشگاه بايد مهد چالشهاي گفتماني باشد ولي اين امر، بدان معني نيست كه دانشگاه، ابزار دست سياسيون قرار بگيرد. وي تأكيد كرد: دانشگاه نه تنها نبايد تحت تأثير القائات سياسي قرار بگيرد؛ بلكه بايد خط دهنده و برنامه\u200cريز جريانات سياسي باشد و مهمترين عنصر پياده شدن اين آرمان، دانشجويان و اعضاي هيات علمي دانشگاهها و در رأس آنها استادان نمونه هستند. وزير علوم با

In [26]:
r = data.iloc[0]
r = r['Title'] + r['Body']
title_body_tokenized = word_tokenize(r)
title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
title_body_tokenized_filtered_lem = [lem.lemmatize(w).replace('#', ' ') for w in title_body_tokenized_filtered]
' '.join(title_body_tokenized_filtered_lem) + ' ' + ' '.join(title_body_tokenized_filtered_stemmed)

'وزير علوم درجمع استاد نمونه سن بازنشستگي استاد نمونه 70 سال افزايش مي\u200cيابد دانشگاه بايد مهد چالشهاي گفتماني خط دهنده برنامه\u200cريز جريانات سياسي وزير علوم جمع استاد نمونه كشور استاد نمونه كشور انتظار مي\u200cرود كه رويكرد دانايي محوري گفتمان علمي يك بحث فرهنگي دانشگاه توسعه رونق بخشید بخش گزارش سرويس صنفي آموزشي خبرگزاري دانشجويان ايران ايسنا دكتر محمد مهدي زاهدي اولين مجمع عمومي استاد نمونه دانشگاه\u200cهاي كشور كه دانشگاه تهران برگزار توصيه تلاش براي دانايي محوري توسعه گفتمان علمي معني تمايل مباحث سياسي نيست بلكه برعكس دانشگاه بايد مهد چالشهاي گفتماني ولي اين امر معني نيست كه دانشگاه ابزار دست سياسيون قرار بگيرد وي تأكيد كرد دانشگاه نبايد تأثير القائات سياسي قرار بگيرد بلكه بايد خط دهنده برنامه\u200cريز جريانات سياسي مهمترين عنصر پياده اين آرمان دانشجويان اعضاي هيات علمي دانشگاه رأس استاد نمونه وزير علوم ذكر اين نكته كه جامعه اطلاعاتي نمي\u200cتوان هيچ تفكري تهديد ارعاب حاكم كرد دانشگاه بايد پرچمدار كرسيهاي آزاد انديشي حاكميت دانايي محوري بايد توجه داشت دار كه ناخودآگاه تأثير

In [28]:
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    title_body_tokenized_filtered_lem = [lem.lemmatize(w).replace('#', ' ') for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_lem) + ' ' + ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [29]:
dataset.head()

title_body category
0  وزير علوم درجمع استاد نمونه سن بازنشستگي استاد...   آموزشي
1  گردهمايي دانش‌آموختگان موسسه آموزش عالي سوره ب...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  همايش يكروزه آسيب شناسي مفهوم روابط عمومي بابل...  اجتماعي
4  وضعيت اقتصادي ميزان تحصيلات والدين مهمترين عوا...   آموزشي

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [32]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
vectorizer.fit(dataset['title_body'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [33]:
X = vectorizer.transform(dataset['title_body'])

In [34]:
X

<10999x1861001 sparse matrix of type '<class 'numpy.float64'>'
	with 6234277 stored elements in Compressed Sparse Row format>

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [37]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [38]:
len(y)

10999

In [39]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [40]:
np.shape(X)

(10999, 1861001)

In [41]:
np.shape(y)

(10999,)

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [44]:
from sklearn import svm

In [45]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
svmc.score(X_test, y_test)

0.8312727272727273

In [47]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.85      0.91      0.88       246\n           1       0.55      0.69      0.61       261\n           2       0.82      0.80      0.81       246\n           3       0.84      0.90      0.87       243\n           4       0.91      0.85      0.88       244\n           5       0.76      0.74      0.75       274\n           6       0.82      0.74      0.78       242\n           7       0.85      0.89      0.87       242\n           8       0.91      0.85      0.88       258\n           9       0.98      0.86      0.92       274\n          10       0.98      0.95      0.97       220\n\n    accuracy                           0.83      2750\n   macro avg       0.84      0.83      0.84      2750\nweighted avg       0.84      0.83      0.83      2750\n'

In [48]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88       246
           1       0.55      0.69      0.61       261
           2       0.82      0.80      0.81       246
           3       0.84      0.90      0.87       243
           4       0.91      0.85      0.88       244
           5       0.76      0.74      0.75       274
           6       0.82      0.74      0.78       242
           7       0.85      0.89      0.87       242
           8       0.91      0.85      0.88       258
           9       0.98      0.86      0.92       274
          10       0.98      0.95      0.97       220

    accuracy                           0.83      2750
   macro avg       0.84      0.83      0.84      2750
weighted avg       0.84      0.83      0.83      2750



In [40]:
print(confusion_matrix(y_test, y_pred))

[[234  10   0   1   0   2   9   1   1   0   1]
 [ 14 179  21   6   8   9   7  16   5   4   1]
 [  3  26 200   0   4   5  12   3   1   2   0]
 [  1   7   4 233   0   2   8   0   0   0   0]
 [  0   4   1   0 219   9   1   2   3   1   0]
 [  2   9  17   1   7 172   5   4  14   2   1]
 [ 14   8   9  25   0   3 201   3   0   0   2]
 [  2  12   5   1   4   5   5 199   1   4   4]
 [  1   8   3   1   3  10   1   2 224   1   0]
 [  0   6   2   1   1   2   0   2   1 237   0]
 [  1   8   0   1   0   3   2   2   0   0 206]]
